blank_issues_enabled: true
contact_links:
  - name: Question
    url: https://discord.gg/livepeer
    about: "Have a question? Join us in the 'lounge' channel on the Livepeer Discord server. We're here to help!"
